# Generated by Django 5.0.6 on 2024-07-10 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('term', models.CharField(choices=[('Short', 'Short'), ('medium', 'medium'), ('long', 'long')], max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('completed', 'Completed')], max_length=10)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.members')),
            ],
        ),
    ]
