# Generated by Django 5.0.6 on 2024-07-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
