# Generated by Django 5.0.6 on 2024-07-06 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('price_per_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_sales', to='members.member')),
            ],
        ),
    ]
